name: Update GitHub Profile

on:
  schedule:
    # Run every 3 hours at :05 past the hour
    - cron: "5 */3 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  update-profile:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Log execution time
        run: |
          echo "⏰ Workflow started at: $(date -u '+%Y-%m-%d %H:%M:%S UTC')"

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Check initial state
        run: |
          echo "📁 Files before generation:"
          ls -la
          echo ""
          echo "Checking existing files:"
          for file in README.md profile.svg profile-dark.svg profile-light.svg; do
            if [ -f "$file" ]; then
              echo "✅ $file exists ($(wc -c < $file) bytes)"
            else
              echo "❌ $file does not exist"
            fi
          done

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install dependencies
        run: npm ci || npm install

      - name: Build TypeScript
        run: |
          echo "🔨 Building TypeScript..."
          npm run build
          echo "📦 Build artifacts:"
          ls -la dist/

      - name: Generate profile
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          GITHUB_USERNAME: ${{ github.repository_owner }}
        run: |
          echo "🚀 Generating profile with both themes..."
          npm run generate
          echo "✅ Generation complete"

      - name: Verify generated files
        run: |
          echo ""
          echo "📋 Verifying all generated files:"
          echo "=================================="
          
          # Check all three SVG files
          MISSING_FILES=0
          
          if [ -f "profile.svg" ]; then
            echo "✅ profile.svg exists ($(wc -c < profile.svg) bytes)"
          else
            echo "❌ profile.svg missing!"
            MISSING_FILES=$((MISSING_FILES + 1))
          fi

          if [ -f "profile-dark.svg" ]; then
            echo "✅ profile-dark.svg exists ($(wc -c < profile-dark.svg) bytes)"
          else
            echo "❌ profile-dark.svg missing!"
            MISSING_FILES=$((MISSING_FILES + 1))
          fi

          if [ -f "profile-light.svg" ]; then
            echo "✅ profile-light.svg exists ($(wc -c < profile-light.svg) bytes)"
          else
            echo "❌ profile-light.svg missing!"
            MISSING_FILES=$((MISSING_FILES + 1))
          fi

          if [ -f "README.md" ]; then
            echo "✅ README.md exists ($(wc -c < README.md) bytes)"
            echo ""
            echo "📄 First 10 lines of README.md:"
            head -n 10 README.md
          else
            echo "❌ README.md missing!"
            MISSING_FILES=$((MISSING_FILES + 1))
          fi

          if [ $MISSING_FILES -gt 0 ]; then
            echo ""
            echo "❌ $MISSING_FILES file(s) missing! Exiting..."
            exit 1
          fi
          
          echo ""
          echo "✅ All files generated successfully!"

      - name: Check git status
        run: |
          echo ""
          echo "📝 Git status:"
          git status
          echo ""
          echo "📊 Git diff summary:"
          git diff --stat
          echo ""
          echo "🔍 Changes in files:"
          git diff --name-only

      - name: Configure git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Add all generated files
        run: |
          echo "➕ Adding all generated files to git..."
          git add -f profile.svg profile-dark.svg profile-light.svg README.md
          echo ""
          echo "📋 Staged files:"
          git diff --staged --name-only

      - name: Commit changes
        id: commit
        run: |
          echo "💾 Attempting to commit changes..."

          # Check if there are changes to commit
          if git diff --staged --quiet; then
            echo "⚠️  No changes detected - files are identical to previous version"
            echo "changed=false" >> $GITHUB_OUTPUT
          else
            echo "✅ Changes detected, committing..."
            git commit -m "🤖 Auto-update profile stats (dark + light themes) [$(date -u '+%Y-%m-%d %H:%M UTC')]"
            echo "changed=true" >> $GITHUB_OUTPUT
            echo "✅ Changes committed successfully"
          fi

      - name: Push changes
        if: steps.commit.outputs.changed == 'true'
        run: |
          echo "🚀 Pushing changes to repository..."
          
          # Try main branch first, fallback to master
          if git push origin main 2>/dev/null; then
            echo "✅ Pushed to main branch"
          elif git push origin master 2>/dev/null; then
            echo "✅ Pushed to master branch"
          else
            echo "❌ Failed to push to repository"
            exit 1
          fi

      - name: Final verification
        if: always()
        run: |
          echo ""
          echo "🎯 Final Status Report:"
          echo "======================="
          echo ""
          
          if [ "${{ steps.commit.outputs.changed }}" == "true" ]; then
            echo "✅ Profile updated successfully!"
            echo "   - Changes committed and pushed"
            echo "   - Both dark and light themes generated"
          else
            echo "ℹ️  No updates needed"
            echo "   - Files unchanged from previous run"
          fi

          echo ""
          echo "📊 Current files in repository:"
          ls -lh profile*.svg README.md 2>/dev/null || echo "Some files may not exist yet"
          
          echo ""
          echo "📝 Latest commit:"
          git log -1 --oneline
          
          echo ""
          echo "⏰ Workflow completed at: $(date -u '+%Y-%m-%d %H:%M:%S UTC')"